/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uesc.lpiii.PalavrasCruzadas;

/*
    Desse jeito que eu to fazendo não vai dar certo,
    não consigo fazer os shapes já prontos e só jogar palavras aleatorias
    pois são poucas palavras e assim ele não vai atender a todos os pedidos
    como é o caso desse codigo agora, provavalmente no dicionario não existam
    as 3 palavras necessarias pra rodar, por isso não está funcionando.
    Preciso gerar os TextBox de acordo com o tamanho das palavras
    e não as palavras de acordo com os TextBox.

    Uma ideia para gerar os TextBox depois das palavras é:
    Ter um vetor de TextBox[] sem especificar tamanho para alocar dinamicamente.
    Pegar uma palavra qualquer, verificar a quantidade de letras.
    Dentro de um laço gerar os TextBox e ter os seguintes passos:
        Gera o TextBox
        Colocar na posição (x, y) que vai ser definido
        Aumentar o valor de x e y
    Fazer isso a quantidade de letras da palavra.
    Desse jeito, teoricamente, vou ter um vetor de TextBox com a quantidade 
    correta de letras e alinhado.
    
    Agora falta tentar pensar o resto, vou dormir pq já ta tarde e tenho que trabalhar.
        
*/


import java.awt.Point;
import java.io.File;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author gabriel
 */
public class UI extends javax.swing.JFrame 
{

    /*
        Declaração de variaves principais
    */
    String[] palavra;
    String[][] bancoPalavras;
    
    LeitorDicionario leitor;
    
    File dicionario;
    
    int tamanhoDicionario;
 
    int quantidadePalavras;
    
    JTextField textPalavra[];
    JTextField bancoText[][];
    
    JLabel lbDica[];
    
    public UI() {
        initComponents();
        
        Point localizacao = new Point(20, 60);
        Random gerador = new Random();
        leitor = new LeitorDicionario();
        dicionario = new File("extras/dicionarioPalCruz.txt");
        tamanhoDicionario = leitor.QuantidadeLinhas(dicionario);
        quantidadePalavras = 0;
        while(quantidadePalavras < 5)
            quantidadePalavras = gerador.nextInt(15) + 1;
        
        bancoPalavras = new String[quantidadePalavras][2];
        
        for(int i = 0; i < quantidadePalavras; i++)
        {
            palavra = leitor.LeituraAleatoria(dicionario, tamanhoDicionario);
            bancoPalavras[i][0] = palavra[0];
            bancoPalavras[i][1] = palavra[1].toLowerCase();
        }
        for(int i = 0; i < quantidadePalavras; i++)
            System.out.println("Palavra " + (i+1) + ": " + bancoPalavras[i][1]);
        
        
        bancoText = new JTextField[quantidadePalavras][];
        lbDica = new JLabel[quantidadePalavras];
        for(int j = 0; j < quantidadePalavras; j++)
        {
            textPalavra = new JTextField[bancoPalavras[j][1].length()];
            lbDica[j] = new JLabel();
            lbDica[j].setSize(30, 30);
            lbDica[j].setLocation(localizacao);
            lbDica[j].setText("Dica");
            lbDica[j].setToolTipText(bancoPalavras[j][0]);
            lbDica[j].setVisible(true);
            this.add(lbDica[j]);
            bancoText[j] = new JTextField[bancoPalavras[j][1].length()];
            for(int i = 0; i < bancoPalavras[j][1].length();i++)
            {
                textPalavra[i] = new JTextField();
                textPalavra[i].setSize(30, 30);
                textPalavra[i].setLocation(localizacao.x + 30 + (i * 30) , localizacao.y);
                textPalavra[i].setVisible(true);
                bancoText[j][i] = textPalavra[i];
                this.add(textPalavra[i]);
            }
            localizacao.setLocation(localizacao.x, localizacao.y + 30);
        }
        
        lbResposta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOk = new javax.swing.JButton();
        lbResposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Palavras Cruzadas");
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));

        btOk.setText("Ok");
        btOk.setToolTipText("");
        btOk.setName(""); // NOI18N
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(lbResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btOk)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btOk))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkPressed
        String[] resposta = new String[quantidadePalavras];
        for(int i = 0; i < quantidadePalavras; i++)
        {
            resposta[i] = "";
            for(int j = 0; j < bancoPalavras[i][1].length(); j++)
                resposta[i] += bancoText[i][j].getText();
            resposta[i] = resposta[i].toLowerCase();
        }
        for(int i = 0; i < quantidadePalavras; i++)
        {
            if(resposta[i].equals(bancoPalavras[i][1]))
                lbResposta.setText("Acertou");
            else
                lbResposta.setText("Errou");
            lbResposta.setVisible(true);
        }
    }//GEN-LAST:event_btOkPressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    //Variaveis da GUI geradas pelo Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbResposta;
    // End of variables declaration//GEN-END:variables
    
}
