/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uesc.lpiii.PalavrasCruzadas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author gabriel
 */

public class UI_Menu extends javax.swing.JFrame {

    /**
     * Creates new form UI_Menu
     */
    public UI_Menu() 
    {
        initMyComponents();
        
    }
    
    private void initMyComponents()
    {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e)
            {
                int result = JOptionPane.showConfirmDialog(null,"Tem certeza que quer sair do jogo?", "Sair do Jogo", JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION)
                {
                    new UI_Menu().setVisible(true);
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                }
            }
        });
        groupButton();
    }
    
    private void groupButton()
    {
        ButtonGroup bg = new ButtonGroup();
        
        bg.add(rbIA);
        bg.add(rbJogador);
        
        rbIA.setSelected(true);
        
        textJogador2.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbIA = new javax.swing.JRadioButton();
        rbJogador = new javax.swing.JRadioButton();
        btJogar = new javax.swing.JButton();
        textJogador1 = new javax.swing.JTextField();
        textJogador2 = new javax.swing.JTextField();
        lbJogador1 = new javax.swing.JLabel();
        lbJogador2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Palavras Cruzadas");

        rbIA.setText("Contra Computador");
        rbIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIAActionPerformed(evt);
            }
        });

        rbJogador.setText("Contra Jogador");
        rbJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJogadorActionPerformed(evt);
            }
        });

        btJogar.setText("Jogar");
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });

        lbJogador1.setText("Jogador 1");

        lbJogador2.setText("Jogador 2");

        jMenu1.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jMenuItem3.setText("Placar de Lideres");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Sobre");
        jMenu2.add(jMenuItem4);

        jMenuItem2.setText("Adicionar Palavra");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbJogador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbJogador1)
                            .addGap(74, 74, 74))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textJogador1)
                            .addComponent(textJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbIA)
                            .addComponent(rbJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btJogar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbJogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbJogador2)
                        .addGap(10, 10, 10)
                        .addComponent(textJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbIA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btJogar)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJogadorActionPerformed
        textJogador2.setEnabled(true);
    }//GEN-LAST:event_rbJogadorActionPerformed

    private void rbIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIAActionPerformed
        textJogador2.setEnabled(false);
    }//GEN-LAST:event_rbIAActionPerformed

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        if((textJogador1.getText().equals("") || textJogador2.getText().equals("")) && rbJogador.isSelected())
            JOptionPane.showMessageDialog(null, "Nome de jogador não pode estar em branco", "Erro", JOptionPane.PLAIN_MESSAGE);
        
        else if(textJogador1.getText().equals("") && rbIA.isSelected())   
            JOptionPane.showMessageDialog(null, "Nome de jogador não pode estar em branco", "Erro", JOptionPane.PLAIN_MESSAGE);
        else if(rbIA.isSelected())
        {
            Jogador jogador1 = new Jogador(textJogador1.getText(), 0);
            Computador IA = new Computador(0);
            new Partida(jogador1, IA);
            this.dispose();
        }
        
        else
        {
            Jogador jogador1 = new Jogador(textJogador1.getText(), 0);
            Jogador jogador2 = new Jogador(textJogador2.getText(), 0);
            new Partida(jogador1, jogador2);
            this.dispose();
        }
            
    }//GEN-LAST:event_btJogarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("teste");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbJogador1;
    private javax.swing.JLabel lbJogador2;
    private javax.swing.JRadioButton rbIA;
    private javax.swing.JRadioButton rbJogador;
    private javax.swing.JTextField textJogador1;
    private javax.swing.JTextField textJogador2;
    // End of variables declaration//GEN-END:variables
}
