/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uesc.lpiii.PalavrasCruzadas;

import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author gabriel
 */
public class UI_Partida extends javax.swing.JFrame 
{

    /*
        Declaração de variaves principais
    */
    String[] palavra;
    String[][] bancoPalavras;
    
    int quantidadePalavras;
    
    JTextField[] textPalavra;
    JTextField[][] bancoText;
    
    JLabel[] lbDica;
    
    int[] posNasPalavras;
    
    int[] posNoPivout;
    
    
    public UI_Partida(String[][] bancoPalavras, int quantidadePalavras, int[] PosNela, int[] PosPivout) 
    {
        this.bancoPalavras = bancoPalavras;
        this.quantidadePalavras = quantidadePalavras;
        posNasPalavras = new int[quantidadePalavras];
        posNoPivout = new int[quantidadePalavras];
        for(int i = 0; i < quantidadePalavras; i++)
        {
            posNasPalavras[i] = PosNela[i];
            posNoPivout[i] = PosPivout[i];
        }
        initMyComponents();
    }
    
    private void initMyComponents()
    {
        initComponents();
        Point localizacao = new Point(350, 50);
        bancoText = new JTextField[quantidadePalavras][];
        lbDica = new JLabel[quantidadePalavras];
        
        
        textPalavra = new JTextField[bancoPalavras[0][1].length()];
        lbDica[0] = new JLabel();
        lbDica[0].setSize(30, 30);
        lbDica[0].setLocation(350, 25);
        lbDica[0].setText("Dica");
        lbDica[0].setToolTipText(bancoPalavras[0][0]);
        lbDica[0].setVisible(true);
        this.add(lbDica[0]);
        bancoText[0] = new JTextField[bancoPalavras[0][1].length()];
        for(int i = 0; i < bancoPalavras[0][1].length(); i++)
        {
            textPalavra[i] = new JTextField();
            textPalavra[i].setSize(30, 30);
            textPalavra[i].setLocation(localizacao);
            textPalavra[i].setVisible(true);
            bancoText[0][i] = textPalavra[i];
            this.add(textPalavra[i]);
            localizacao.setLocation(localizacao.x, localizacao.y + 35);
        }
        montaTextField();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    private void montaTextField()
    {
        Point localPivout = new Point(350, 40); 
        for(int i = 1; i < quantidadePalavras; i++)
        {
                                              // -1 * pra ficar negativo | + 1 pq da label é da label                  | + 10 pq da label         
            Point localPalavra = new Point(localPivout.x +( -1 * ((posNasPalavras[i] + 1) * 35)), localPivout.y + (posNoPivout[i] * 35) + 10);
            
            textPalavra = new JTextField[bancoPalavras[i][1].length()];
            lbDica[i] = new JLabel();
            lbDica[i].setSize(30, 30);
            lbDica[i].setLocation(localPalavra);
            lbDica[i].setText("Dica");
            lbDica[i].setToolTipText(bancoPalavras[i][0]);
            lbDica[i].setVisible(true);
            this.add(lbDica[i]);
            localPalavra.setLocation(localPalavra.x + 35, localPalavra.y);
            bancoText[i] = new JTextField[bancoPalavras[i][1].length()];
            for(int j = 0; j < bancoPalavras[i][1].length(); j++)
            {
                if(j != posNasPalavras[i])
                {
                    textPalavra[j] = new JTextField();
                    textPalavra[j].setSize(30, 30);
                    textPalavra[j].setLocation(localPalavra);
                    textPalavra[j].setVisible(true);
                    bancoText[i][j] = textPalavra[j];
                    this.add(textPalavra[j]);
                }
                else
                    bancoText[i][j] = bancoText[0][posNoPivout[i]];
                localPalavra.setLocation(localPalavra.x + 35, localPalavra.y);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProximoJogo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Palavras Cruzadas");
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));

        btProximoJogo.setText("Proximo Jogo");
        btProximoJogo.setToolTipText("");
        btProximoJogo.setName(""); // NOI18N
        btProximoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoJogoPressed(evt);
            }
        });

        jButton1.setText("Novo Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProximoJogo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btProximoJogo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProximoJogoPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoJogoPressed
      
    }//GEN-LAST:event_btProximoJogoPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new UI_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    //Variaveis da GUI geradas pelo Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProximoJogo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
